// GERADO AUTOMATICAMENTE por scripts/gerar-dados.ts a partir de docs/olympos-deck.json.
// Não edite manualmente — rode `pnpm --filter @olympos/motor gerar:dados`.

import type { Lenda } from '../tipos.js';

export const LENDAS: Lenda[] = [
  { id: "L1-ETE-01", nivel: 1, dominio: "eter", kleos: 0, custo: { eter: 0, oceano: 1, terra: 1, chama: 1, sombra: 1 }, argo: 0, chronos: false, nome: "Ambrosia" },
  { id: "L1-ETE-02", nivel: 1, dominio: "eter", kleos: 0, custo: { eter: 0, oceano: 1, terra: 2, chama: 1, sombra: 1 }, argo: 1, chronos: false, nome: "Néctar Divino" },
  { id: "L1-ETE-03", nivel: 1, dominio: "eter", kleos: 0, custo: { eter: 0, oceano: 2, terra: 2, chama: 0, sombra: 1 }, argo: 0, chronos: false, nome: "Coroa de Louros" },
  { id: "L1-ETE-04", nivel: 1, dominio: "eter", kleos: 0, custo: { eter: 1, oceano: 0, terra: 0, chama: 1, sombra: 3 }, argo: 0, chronos: false, nome: "Sandálias Aladas" },
  { id: "L1-ETE-05", nivel: 1, dominio: "eter", kleos: 0, custo: { eter: 0, oceano: 0, terra: 0, chama: 2, sombra: 1 }, argo: 0, chronos: false, nome: "Pena de Ícaro" },
  { id: "L1-ETE-06", nivel: 1, dominio: "eter", kleos: 0, custo: { eter: 0, oceano: 2, terra: 0, chama: 2, sombra: 0 }, argo: 1, chronos: false, nome: "Cálice de Hebe" },
  { id: "L1-ETE-07", nivel: 1, dominio: "eter", kleos: 0, custo: { eter: 0, oceano: 0, terra: 0, chama: 3, sombra: 0 }, argo: 0, chronos: false, nome: "Chama de Héstia" },
  { id: "L1-ETE-08", nivel: 1, dominio: "eter", kleos: 1, custo: { eter: 0, oceano: 0, terra: 4, chama: 0, sombra: 0 }, argo: 0, chronos: false, nome: "Fio de Ariadne" },
  { id: "L1-OCE-01", nivel: 1, dominio: "oceano", kleos: 0, custo: { eter: 1, oceano: 0, terra: 1, chama: 1, sombra: 1 }, argo: 0, chronos: false, nome: "Concha de Tritão" },
  { id: "L1-OCE-02", nivel: 1, dominio: "oceano", kleos: 0, custo: { eter: 1, oceano: 0, terra: 1, chama: 2, sombra: 1 }, argo: 1, chronos: false, nome: "Rede do Pescador" },
  { id: "L1-OCE-03", nivel: 1, dominio: "oceano", kleos: 0, custo: { eter: 1, oceano: 0, terra: 2, chama: 2, sombra: 0 }, argo: 0, chronos: false, nome: "Ânfora do Egeu" },
  { id: "L1-OCE-04", nivel: 1, dominio: "oceano", kleos: 0, custo: { eter: 3, oceano: 1, terra: 0, chama: 0, sombra: 1 }, argo: 0, chronos: false, nome: "Espuma Sagrada" },
  { id: "L1-OCE-05", nivel: 1, dominio: "oceano", kleos: 0, custo: { eter: 1, oceano: 0, terra: 0, chama: 0, sombra: 2 }, argo: 0, chronos: false, nome: "Remo do Argo" },
  { id: "L1-OCE-06", nivel: 1, dominio: "oceano", kleos: 0, custo: { eter: 0, oceano: 0, terra: 2, chama: 0, sombra: 2 }, argo: 1, chronos: false, nome: "Pérola de Tétis" },
  { id: "L1-OCE-07", nivel: 1, dominio: "oceano", kleos: 0, custo: { eter: 0, oceano: 0, terra: 0, chama: 0, sombra: 3 }, argo: 0, chronos: false, nome: "Sal do Mar Jônio" },
  { id: "L1-OCE-08", nivel: 1, dominio: "oceano", kleos: 1, custo: { eter: 0, oceano: 0, terra: 0, chama: 4, sombra: 0 }, argo: 0, chronos: false, nome: "Âncora de Bronze" },
  { id: "L1-TER-01", nivel: 1, dominio: "terra", kleos: 0, custo: { eter: 1, oceano: 1, terra: 0, chama: 1, sombra: 1 }, argo: 0, chronos: false, nome: "Espiga Dourada" },
  { id: "L1-TER-02", nivel: 1, dominio: "terra", kleos: 0, custo: { eter: 1, oceano: 1, terra: 0, chama: 1, sombra: 2 }, argo: 1, chronos: false, nome: "Oliveira Sagrada" },
  { id: "L1-TER-03", nivel: 1, dominio: "terra", kleos: 0, custo: { eter: 0, oceano: 1, terra: 0, chama: 2, sombra: 2 }, argo: 0, chronos: false, nome: "Cornucópia" },
  { id: "L1-TER-04", nivel: 1, dominio: "terra", kleos: 0, custo: { eter: 1, oceano: 3, terra: 1, chama: 0, sombra: 0 }, argo: 0, chronos: false, nome: "Tirso" },
  { id: "L1-TER-05", nivel: 1, dominio: "terra", kleos: 0, custo: { eter: 2, oceano: 1, terra: 0, chama: 0, sombra: 0 }, argo: 0, chronos: false, nome: "Cajado do Pastor" },
  { id: "L1-TER-06", nivel: 1, dominio: "terra", kleos: 0, custo: { eter: 2, oceano: 0, terra: 0, chama: 2, sombra: 0 }, argo: 1, chronos: false, nome: "Vinha do Egeu" },
  { id: "L1-TER-07", nivel: 1, dominio: "terra", kleos: 0, custo: { eter: 3, oceano: 0, terra: 0, chama: 0, sombra: 0 }, argo: 0, chronos: false, nome: "Semente de Perséfone" },
  { id: "L1-TER-08", nivel: 1, dominio: "terra", kleos: 1, custo: { eter: 0, oceano: 0, terra: 0, chama: 0, sombra: 4 }, argo: 0, chronos: false, nome: "Mel do Himeto" },
  { id: "L1-CHA-01", nivel: 1, dominio: "chama", kleos: 0, custo: { eter: 1, oceano: 1, terra: 1, chama: 0, sombra: 1 }, argo: 0, chronos: false, nome: "Tocha de Prometeu" },
  { id: "L1-CHA-02", nivel: 1, dominio: "chama", kleos: 0, custo: { eter: 2, oceano: 1, terra: 1, chama: 0, sombra: 1 }, argo: 1, chronos: false, nome: "Martelo de Bronze" },
  { id: "L1-CHA-03", nivel: 1, dominio: "chama", kleos: 0, custo: { eter: 2, oceano: 0, terra: 1, chama: 0, sombra: 2 }, argo: 0, chronos: false, nome: "Fole da Forja" },
  { id: "L1-CHA-04", nivel: 1, dominio: "chama", kleos: 0, custo: { eter: 0, oceano: 1, terra: 3, chama: 1, sombra: 0 }, argo: 0, chronos: false, nome: "Carvão do Etna" },
  { id: "L1-CHA-05", nivel: 1, dominio: "chama", kleos: 0, custo: { eter: 0, oceano: 2, terra: 1, chama: 0, sombra: 0 }, argo: 0, chronos: false, nome: "Lança de Bronze" },
  { id: "L1-CHA-06", nivel: 1, dominio: "chama", kleos: 0, custo: { eter: 0, oceano: 2, terra: 0, chama: 0, sombra: 2 }, argo: 1, chronos: false, nome: "Braseiro Votivo" },
  { id: "L1-CHA-07", nivel: 1, dominio: "chama", kleos: 0, custo: { eter: 0, oceano: 3, terra: 0, chama: 0, sombra: 0 }, argo: 0, chronos: false, nome: "Fagulha de Hefesto" },
  { id: "L1-CHA-08", nivel: 1, dominio: "chama", kleos: 1, custo: { eter: 4, oceano: 0, terra: 0, chama: 0, sombra: 0 }, argo: 0, chronos: false, nome: "Elmo Coríntio" },
  { id: "L1-SOM-01", nivel: 1, dominio: "sombra", kleos: 0, custo: { eter: 1, oceano: 1, terra: 1, chama: 1, sombra: 0 }, argo: 0, chronos: false, nome: "Óbolo de Caronte" },
  { id: "L1-SOM-02", nivel: 1, dominio: "sombra", kleos: 0, custo: { eter: 1, oceano: 2, terra: 1, chama: 1, sombra: 0 }, argo: 1, chronos: false, nome: "Romã de Perséfone" },
  { id: "L1-SOM-03", nivel: 1, dominio: "sombra", kleos: 0, custo: { eter: 2, oceano: 2, terra: 0, chama: 1, sombra: 0 }, argo: 0, chronos: false, nome: "Flor de Asfódelo" },
  { id: "L1-SOM-04", nivel: 1, dominio: "sombra", kleos: 0, custo: { eter: 0, oceano: 0, terra: 1, chama: 3, sombra: 1 }, argo: 0, chronos: false, nome: "Mortalha de Linho" },
  { id: "L1-SOM-05", nivel: 1, dominio: "sombra", kleos: 0, custo: { eter: 0, oceano: 0, terra: 2, chama: 1, sombra: 0 }, argo: 0, chronos: false, nome: "Urna Funerária" },
  { id: "L1-SOM-06", nivel: 1, dominio: "sombra", kleos: 0, custo: { eter: 2, oceano: 0, terra: 2, chama: 0, sombra: 0 }, argo: 1, chronos: false, nome: "Véu de Nix" },
  { id: "L1-SOM-07", nivel: 1, dominio: "sombra", kleos: 0, custo: { eter: 0, oceano: 0, terra: 3, chama: 0, sombra: 0 }, argo: 0, chronos: false, nome: "Cinzas do Estige" },
  { id: "L1-SOM-08", nivel: 1, dominio: "sombra", kleos: 1, custo: { eter: 0, oceano: 4, terra: 0, chama: 0, sombra: 0 }, argo: 0, chronos: false, nome: "Chave do Tártaro" },
  { id: "L2-ETE-01", nivel: 2, dominio: "eter", kleos: 1, custo: { eter: 0, oceano: 0, terra: 2, chama: 3, sombra: 2 }, argo: 1, chronos: false, nome: "Íris" },
  { id: "L2-ETE-02", nivel: 2, dominio: "eter", kleos: 1, custo: { eter: 2, oceano: 0, terra: 3, chama: 3, sombra: 0 }, argo: 0, chronos: false, nome: "Ganimedes" },
  { id: "L2-ETE-03", nivel: 2, dominio: "eter", kleos: 2, custo: { eter: 0, oceano: 5, terra: 0, chama: 0, sombra: 0 }, argo: 0, chronos: false, nome: "Éolo" },
  { id: "L2-ETE-04", nivel: 2, dominio: "eter", kleos: 2, custo: { eter: 0, oceano: 1, terra: 4, chama: 2, sombra: 0 }, argo: 1, chronos: false, nome: "Pégaso" },
  { id: "L2-ETE-05", nivel: 2, dominio: "eter", kleos: 2, custo: { eter: 0, oceano: 0, terra: 0, chama: 5, sombra: 3 }, argo: 0, chronos: false, nome: "Orfeu" },
  { id: "L2-ETE-06", nivel: 2, dominio: "eter", kleos: 3, custo: { eter: 6, oceano: 0, terra: 0, chama: 0, sombra: 0 }, argo: 0, chronos: false, nome: "Eos" },
  { id: "L2-OCE-01", nivel: 2, dominio: "oceano", kleos: 1, custo: { eter: 2, oceano: 0, terra: 0, chama: 2, sombra: 3 }, argo: 1, chronos: false, nome: "Nereida" },
  { id: "L2-OCE-02", nivel: 2, dominio: "oceano", kleos: 1, custo: { eter: 0, oceano: 2, terra: 0, chama: 3, sombra: 3 }, argo: 0, chronos: false, nome: "Tritão" },
  { id: "L2-OCE-03", nivel: 2, dominio: "oceano", kleos: 2, custo: { eter: 0, oceano: 0, terra: 5, chama: 0, sombra: 0 }, argo: 0, chronos: false, nome: "Sirene" },
  { id: "L2-OCE-04", nivel: 2, dominio: "oceano", kleos: 2, custo: { eter: 0, oceano: 0, terra: 1, chama: 4, sombra: 2 }, argo: 1, chronos: false, nome: "Cila" },
  { id: "L2-OCE-05", nivel: 2, dominio: "oceano", kleos: 2, custo: { eter: 3, oceano: 0, terra: 0, chama: 0, sombra: 5 }, argo: 0, chronos: false, nome: "Caríbdis" },
  { id: "L2-OCE-06", nivel: 2, dominio: "oceano", kleos: 3, custo: { eter: 0, oceano: 6, terra: 0, chama: 0, sombra: 0 }, argo: 0, chronos: false, nome: "Jasão" },
  { id: "L2-TER-01", nivel: 2, dominio: "terra", kleos: 1, custo: { eter: 3, oceano: 2, terra: 0, chama: 0, sombra: 2 }, argo: 1, chronos: false, nome: "Dríade" },
  { id: "L2-TER-02", nivel: 2, dominio: "terra", kleos: 1, custo: { eter: 3, oceano: 0, terra: 2, chama: 0, sombra: 3 }, argo: 0, chronos: false, nome: "Sátiro" },
  { id: "L2-TER-03", nivel: 2, dominio: "terra", kleos: 2, custo: { eter: 0, oceano: 0, terra: 0, chama: 5, sombra: 0 }, argo: 0, chronos: false, nome: "Centauro" },
  { id: "L2-TER-04", nivel: 2, dominio: "terra", kleos: 2, custo: { eter: 2, oceano: 0, terra: 0, chama: 1, sombra: 4 }, argo: 1, chronos: false, nome: "Quíron" },
  { id: "L2-TER-05", nivel: 2, dominio: "terra", kleos: 2, custo: { eter: 5, oceano: 3, terra: 0, chama: 0, sombra: 0 }, argo: 0, chronos: false, nome: "Atalanta" },
  { id: "L2-TER-06", nivel: 2, dominio: "terra", kleos: 3, custo: { eter: 0, oceano: 0, terra: 6, chama: 0, sombra: 0 }, argo: 0, chronos: false, nome: "Javali de Erimanto" },
  { id: "L2-CHA-01", nivel: 2, dominio: "chama", kleos: 1, custo: { eter: 2, oceano: 3, terra: 2, chama: 0, sombra: 0 }, argo: 1, chronos: false, nome: "Ciclope" },
  { id: "L2-CHA-02", nivel: 2, dominio: "chama", kleos: 1, custo: { eter: 3, oceano: 3, terra: 0, chama: 2, sombra: 0 }, argo: 0, chronos: false, nome: "Quimera" },
  { id: "L2-CHA-03", nivel: 2, dominio: "chama", kleos: 2, custo: { eter: 0, oceano: 0, terra: 0, chama: 0, sombra: 5 }, argo: 0, chronos: false, nome: "Fênix" },
  { id: "L2-CHA-04", nivel: 2, dominio: "chama", kleos: 2, custo: { eter: 4, oceano: 2, terra: 0, chama: 0, sombra: 1 }, argo: 1, chronos: false, nome: "Talos" },
  { id: "L2-CHA-05", nivel: 2, dominio: "chama", kleos: 2, custo: { eter: 0, oceano: 5, terra: 3, chama: 0, sombra: 0 }, argo: 0, chronos: false, nome: "Belerofonte" },
  { id: "L2-CHA-06", nivel: 2, dominio: "chama", kleos: 3, custo: { eter: 0, oceano: 0, terra: 0, chama: 6, sombra: 0 }, argo: 0, chronos: false, nome: "Aquiles" },
  { id: "L2-SOM-01", nivel: 2, dominio: "sombra", kleos: 1, custo: { eter: 0, oceano: 2, terra: 3, chama: 2, sombra: 0 }, argo: 1, chronos: false, nome: "Harpia" },
  { id: "L2-SOM-02", nivel: 2, dominio: "sombra", kleos: 1, custo: { eter: 0, oceano: 3, terra: 3, chama: 0, sombra: 2 }, argo: 0, chronos: false, nome: "Erínia" },
  { id: "L2-SOM-03", nivel: 2, dominio: "sombra", kleos: 2, custo: { eter: 5, oceano: 0, terra: 0, chama: 0, sombra: 0 }, argo: 0, chronos: false, nome: "Medusa" },
  { id: "L2-SOM-04", nivel: 2, dominio: "sombra", kleos: 2, custo: { eter: 1, oceano: 4, terra: 2, chama: 0, sombra: 0 }, argo: 1, chronos: false, nome: "Hidra de Lerna" },
  { id: "L2-SOM-05", nivel: 2, dominio: "sombra", kleos: 2, custo: { eter: 0, oceano: 0, terra: 5, chama: 3, sombra: 0 }, argo: 0, chronos: false, nome: "Caronte" },
  { id: "L2-SOM-06", nivel: 2, dominio: "sombra", kleos: 3, custo: { eter: 0, oceano: 0, terra: 0, chama: 0, sombra: 6 }, argo: 0, chronos: false, nome: "Cérbero" },
  { id: "L3-ETE-01", nivel: 3, dominio: "eter", kleos: 3, custo: { eter: 0, oceano: 3, terra: 3, chama: 5, sombra: 3 }, argo: 1, chronos: true, nome: "Hélios" },
  { id: "L3-ETE-02", nivel: 3, dominio: "eter", kleos: 4, custo: { eter: 0, oceano: 0, terra: 0, chama: 7, sombra: 0 }, argo: 0, chronos: true, nome: "Selene" },
  { id: "L3-ETE-03", nivel: 3, dominio: "eter", kleos: 4, custo: { eter: 3, oceano: 0, terra: 0, chama: 6, sombra: 3 }, argo: 0, chronos: true, nome: "Hipérion" },
  { id: "L3-ETE-04", nivel: 3, dominio: "eter", kleos: 5, custo: { eter: 3, oceano: 0, terra: 0, chama: 7, sombra: 0 }, argo: 2, chronos: true, nome: "Urano" },
  { id: "L3-OCE-01", nivel: 3, dominio: "oceano", kleos: 3, custo: { eter: 3, oceano: 0, terra: 3, chama: 3, sombra: 5 }, argo: 1, chronos: true, nome: "Nereu" },
  { id: "L3-OCE-02", nivel: 3, dominio: "oceano", kleos: 4, custo: { eter: 0, oceano: 0, terra: 0, chama: 0, sombra: 7 }, argo: 0, chronos: true, nome: "Ponto" },
  { id: "L3-OCE-03", nivel: 3, dominio: "oceano", kleos: 4, custo: { eter: 3, oceano: 3, terra: 0, chama: 0, sombra: 6 }, argo: 0, chronos: true, nome: "Tétis" },
  { id: "L3-OCE-04", nivel: 3, dominio: "oceano", kleos: 5, custo: { eter: 0, oceano: 3, terra: 0, chama: 0, sombra: 7 }, argo: 2, chronos: true, nome: "Oceano" },
  { id: "L3-TER-01", nivel: 3, dominio: "terra", kleos: 3, custo: { eter: 5, oceano: 3, terra: 0, chama: 3, sombra: 3 }, argo: 1, chronos: true, nome: "Anteu" },
  { id: "L3-TER-02", nivel: 3, dominio: "terra", kleos: 4, custo: { eter: 7, oceano: 0, terra: 0, chama: 0, sombra: 0 }, argo: 0, chronos: true, nome: "Ládon" },
  { id: "L3-TER-03", nivel: 3, dominio: "terra", kleos: 4, custo: { eter: 6, oceano: 3, terra: 3, chama: 0, sombra: 0 }, argo: 0, chronos: true, nome: "Reia" },
  { id: "L3-TER-04", nivel: 3, dominio: "terra", kleos: 5, custo: { eter: 7, oceano: 0, terra: 3, chama: 0, sombra: 0 }, argo: 2, chronos: true, nome: "Gaia" },
  { id: "L3-CHA-01", nivel: 3, dominio: "chama", kleos: 3, custo: { eter: 3, oceano: 5, terra: 3, chama: 0, sombra: 3 }, argo: 1, chronos: true, nome: "Briareu" },
  { id: "L3-CHA-02", nivel: 3, dominio: "chama", kleos: 4, custo: { eter: 0, oceano: 7, terra: 0, chama: 0, sombra: 0 }, argo: 0, chronos: true, nome: "Tifão" },
  { id: "L3-CHA-03", nivel: 3, dominio: "chama", kleos: 4, custo: { eter: 0, oceano: 6, terra: 3, chama: 3, sombra: 0 }, argo: 0, chronos: true, nome: "Prometeu" },
  { id: "L3-CHA-04", nivel: 3, dominio: "chama", kleos: 5, custo: { eter: 0, oceano: 7, terra: 0, chama: 3, sombra: 0 }, argo: 2, chronos: true, nome: "Héracles" },
  { id: "L3-SOM-01", nivel: 3, dominio: "sombra", kleos: 3, custo: { eter: 3, oceano: 3, terra: 5, chama: 3, sombra: 0 }, argo: 1, chronos: true, nome: "Tânatos" },
  { id: "L3-SOM-02", nivel: 3, dominio: "sombra", kleos: 4, custo: { eter: 0, oceano: 0, terra: 7, chama: 0, sombra: 0 }, argo: 0, chronos: true, nome: "Érebo" },
  { id: "L3-SOM-03", nivel: 3, dominio: "sombra", kleos: 4, custo: { eter: 0, oceano: 0, terra: 6, chama: 3, sombra: 3 }, argo: 0, chronos: true, nome: "Nix" },
  { id: "L3-SOM-04", nivel: 3, dominio: "sombra", kleos: 5, custo: { eter: 0, oceano: 0, terra: 7, chama: 0, sombra: 3 }, argo: 2, chronos: true, nome: "Cronos" },
];

export const LENDA_POR_ID: Record<string, Lenda> = Object.fromEntries(
  LENDAS.map((l) => [l.id, l]),
);
